// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxmw0UQCZtA4r5Zz8AZ1f-wfQBF0f-j7s',
    appId: '1:848438809694:web:403f2173b0161b9b9710cf',
    messagingSenderId: '848438809694',
    projectId: 'artverse-33920',
    authDomain: 'artverse-33920.firebaseapp.com',
    storageBucket: 'artverse-33920.firebasestorage.app',
    measurementId: 'G-2LES4GF6QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZpAnGsyXi99E1A4IRz3dgOlbJggk_3E',
    appId: '1:848438809694:android:a7884d3d75a1be4c9710cf',
    messagingSenderId: '848438809694',
    projectId: 'artverse-33920',
    storageBucket: 'artverse-33920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv1YTqnf7p3z2R0493etGFiGNU2xz7Ci0',
    appId: '1:848438809694:ios:f9c8820439e89cb59710cf',
    messagingSenderId: '848438809694',
    projectId: 'artverse-33920',
    storageBucket: 'artverse-33920.firebasestorage.app',
    iosBundleId: 'com.artverse.artverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv1YTqnf7p3z2R0493etGFiGNU2xz7Ci0',
    appId: '1:848438809694:ios:f9c8820439e89cb59710cf',
    messagingSenderId: '848438809694',
    projectId: 'artverse-33920',
    storageBucket: 'artverse-33920.firebasestorage.app',
    iosBundleId: 'com.artverse.artverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxmw0UQCZtA4r5Zz8AZ1f-wfQBF0f-j7s',
    appId: '1:848438809694:web:6353af367141f03c9710cf',
    messagingSenderId: '848438809694',
    projectId: 'artverse-33920',
    authDomain: 'artverse-33920.firebaseapp.com',
    storageBucket: 'artverse-33920.firebasestorage.app',
    measurementId: 'G-NDRSMCBMNK',
  );
}
